### ISSUE TITLE
Minor issue with not common

### ISSUE THREAD

**Issue by Fridan99** [jessev14/custom-rarities-and-currencies#3]
I have not used the module yet.... but I have one question

How are the non common objects reflected?

Not common

Or 

Uncommon

As I have seen in the screenshot they appear as not common. 

According to the PHB and the DMG refer to these objects as “uncommon”.

It's really not a problem 🤣, just a note in case you want to put it as defined in the books.

I think that your module will be very useful to quickly differentiate the rarity of the objects. 

Here an official example

https://media.wizards.com/2014/downloads/dnd/MagicItemsRarity_printerfriendly.pdf

**Comment by jessev14** [comment]
This module lets you change the name of the rarities. The default name is "Uncommon" but the screenshot shows how this module can change it to "Not Common".
