### ISSUE TITLE
Items no longer display appropriate colours (Foundry v9, Custom Rarities & Currencies v1.0.0)

### ISSUE THREAD

**Issue by Janner3D** [jessev14/custom-rarities-and-currencies#4]
![image](https://user-images.githubusercontent.com/35965176/190621495-29e609b8-c51d-416c-aa51-af09d1139f69.png)
The items no longer seem to display the appropriate colours, except when displayed in the directory.

**Comment by jessev14** [comment]
That is a feature of the Rarity Colors module which has not been updated for V10.
